version: '3.8'
services:
  app:
    build: .
    expose: 
      - "1234"
    container_name: sb
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: sb-nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network
    volumes:
      # Mount the custom Nginx config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the static files (in the build directory) so Nginx can serve them
      - ./build:/usr/share/nginx/html:ro

networks:
  app-network:
    driver: bridge

